services:
  db:
    image: postgres:18-alpine
    container_name: dancerapp-postgres-dev
    environment:
      POSTGRES_PASSWORD: aPasswordToReplace
    volumes:
      - dancer_postgres_data_dev:/var/lib/postgresql
    ports:
      - "127.0.0.1:5433:5433"  # Expose to localhost only
    command: -p 5433
    networks:
      - back-end-db-network
  dancer-back-end-dev:
    # image: dancer-app-backend
    networks:
      - back-end-db-network
    depends_on:
      - db
    build: 
      # context: ./back-end
      dockerfile: ./dancer-dev.dockerfile
    # Open a public port so the back-end can be debugged if necessary
    ports:
        - "127.0.0.1:5000:5000"
    volumes:
      - type: bind
        source: ./back-end
        target: /app
  vue-front-end-dev:
    depends_on:
      - dancer-back-end-dev
    build:
      # context: .
      dockerfile: ./vue-dev.dockerfile
    ports:
      - "127.0.0.1:5173:5173"
    volumes:
      # Bind mount source for hot module replacement
      - ./vue-front-end:/app
      # Anonymous volume to preserve container's node_modules
      # also obscures host `node_modules` to prevent conflicts for the container
      - /app/node_modules
  
volumes:
  dancer_postgres_data_dev:

networks:
  back-end-db-network:
    driver: bridge

# volumes:
#   src:
#     driver: local
#     driver_opts:
#       type: none
#       o: bind
#       device: ./app