package DancerApp;
use Dancer2;
use Dancer2::Plugin::Database;

use strict;
use warnings;

our $VERSION = '0.1';

hook 'database_connected' => sub {
    my $dbh = shift;

    $dbh->prepare('
    CREATE TABLE IF NOT EXISTS public."Notes"
    (
        "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
        "Title" text COLLATE pg_catalog."default" NOT NULL,
        "Content" text COLLATE pg_catalog."default",
        "CreatedAt" timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
        "UpdatedAt" timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
        CONSTRAINT "PK_Notes" PRIMARY KEY ("Id")
    )
    ')->execute;

    $dbh->prepare('
    INSERT INTO public."Notes"("Id", "Title", "Content", "CreatedAt", "UpdatedAt")
	VALUES (1, \'Hello!\', \'This is a note created on DB startup!\', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
    ON CONFLICT ("Id") DO NOTHING;
    ')->execute;
};

# hook 'database_connection_failed' => sub {
#     $conn_state = 'failed';
# };

# hook 'database_error' => sub {
#     $conn_state = 'error';
# };

get '/' => sub {
    template 'index' => { 'title' => 'DancerApp' };
};

prefix '/api' => sub {
    get '/test' => sub {
        content_type("application/json");
        response_header('Access-Control-Allow-Origin' => '*');
        response_header('Access-Control-Allow-Methods' => 'GET');
        response_header('Access-Control-Allow-Headers' => 'Content-Type, X-Requested-With');
        return to_json({"data-from" => "dancer2"});
    };

    options '/test' => sub {
        response_header('Access-Control-Allow-Origin' => '*');
        response_header('Access-Control-Allow-Methods' => 'GET');
        return;
    };

    get 'note-by-id' => '/notes/:id' => sub {
        response_header('Access-Control-Allow-Origin' => '*');
        response_header('Access-Control-Allow-Methods' => 'GET');
        content_type("application/json");

        # my $sth = database->prepare(
        #     'SELECT * FROM notes WHERE id = ?',
        # );
        # $sth->execute(params->{id});
        
        return to_json(database->quick_select('Notes', { Id => params->{id} }));
    };

};

get '/search' => sub {
    my $query = query_parameters->get('note-name');

    my $sth = database->prepare(
    'SELECT "Id", "Title" FROM "Notes" WHERE "Title" LIKE \'%\' || :query || \'%\'',
    );
    $sth->bind_param(':query', $query);

    $sth->execute;
    my @res = @{$sth->fetchall_arrayref};

    foreach my $elem (@res) {
        push(@$elem, uri_for_route('note-by-id', { id => $elem->[0] }));
    }

    template 'note-search' => {note_query => $query, notes => \@res};
};


# TODO: Remove
# get 'note-by-id' => '/:id' => sub {
#     response_header('Access-Control-Allow-Origin' => '*');
#         response_header('Access-Control-Allow-Methods' => 'GET');
#     content_type("application/json");

#     # my $sth = database->prepare(
#     #     'SELECT * FROM notes WHERE id = ?',
#     # );
#     # $sth->execute(params->{id});
    
#     return to_json(database->quick_select('Notes', { Id => params->{id} }));
# };

true;
